import type { Metadata } from "next";
import Header from "@components/Header";
import Navbar from "@components/Navbar"
import "./globals.css";

export const metadata: Metadata = {
  title: "thingstodo3",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
